---

commands: bundle install --jobs=3 --retry=3

# Exclude these hosts and IP addresses from network monitoring
host_whitelist:
  - 10.0.2.2 # VirtualBox's address
  - bundler.rubygems.org
  - index.rubygems.org
  - rubygems.global.ssl.fastly.net
  - rubygems.org

# Files or directories which should be included or excluded from evidence collection
evidence_files:
  exclude:
    - /backup
    - /dev
    - /evidence
    - /home/vagrant/.gem
    - /home/vagrant/.rvm
    - /home/vagrant/repo
    - /lost+found
    - /media
    - /mnt
    - /proc
    - /run
    - /sys
    - /tmp
    - /vagrant
    - /var/lock
    - /var/log
    - /var/run
    - /var/tmp
  include:
    - /bin
    - /boot
    - /etc
    - /home
    - /lib
    - /opt
    - /root
    - /sbin
    - /selinux
    - /srv
    - /usr
    - /var
